### ISSUE TITLE
Accept `out.pdb` as a parameter

### ISSUE THREAD

**Issue by joaomcteixeira** [osita-sunday-nnyigide/Pras_Server#2]
Hi again :wink:

I have been using `PRAS` now extensively on many PDBs. The fact that the output is fixed to `out.pdb` is a limitation when parallelizing multiple `PRAS` processes. It would be great to have a `-o`  option to define the output file name.

Many thanks!

**Comment by osita-sunday-nnyigide** [comment]
Yes, you are correct. I will do that over the weekend for both the python and c++ distributions.

Thank you!

**Comment by joaomcteixeira** [comment]
Many thanks!

**Comment by osita-sunday-nnyigide** [comment]
Hello, 

I have added the option for user to supply output name [-o]. Also user should use [-k] flag to keep the log file otherwise
it reverts to default behaviour (i.e. PRAS removes log file and output file each time it is run). see INSTALL.md

If one processes multiple PDBs with [-o] and [-k] flags, the log file will include the name of each PDB for one
to know which PDB missing atoms were fixed.

Thank you.

**Comment by joaomcteixeira** [comment]
Hi,
Many thanks. I will test it and give you feedback asap. :+1:

**Comment by osita-sunday-nnyigide** [comment]
Thank you!

**Comment by joaomcteixeira** [comment]
I have tested it, and everything is working so far. The concatenated log feature is also working.

Many thanks :+1: `Pras_Server` performs really well. I look forward to citing `PRAS` in our next publications.

Best!

**Comment by osita-sunday-nnyigide** [comment]
Thank you!
